### PR TITLE
Refactor/docker

### PR DESCRIPTION
**Pull request by kojiadrianojr**
I changed the docker version and updated the readme. It is still a work in progress, and a review would be a great help. 

I added a docker-compose.yml file and this docker version now uses a cli to run the checkers.

### CODE REVIEW

**Comment by jinolacson** [comment]
Noted, we'll review it tomorrow before merging.

**Comment by kojiadrianojr** [comment]
One more thing, this version doesn't have yet the student list per mentor.

**Comment by jinolacson** [comment]
That would be fine that's only additional s in our grading utls

**Comment by kojiadrianojr** [comment]
Sir I already created a new PR with those features.

**Pull request merged**
